BRACKET_INNER_CHANNEL_NARROW = 6.75;
CUBBY_WIDTH = 336;
BRACKET_DEPTH  = 50;
MOUNTING_DEPTH = 14;
BRACKET_HEIGHT = 17;
BRACKET_WIDTH = 10;
BRACKET_LIP_WIDTH = 3;
BRACKET_THICKNESS = 3;

SCREW_FLANGE_HEIGHT = 10;
SCREW_FLANGE_DEPTH = 10;

SNAP_PIN_GAP = 1.5;
SNAP_PIN_TOOTH_WIDTH = 3;
SNAP_PIN_THICKNESS = 1.5;
SNAP_PIN_LENGTH = 5;
SNAP_PIN_LIP_DEPTH = 1.75;
SNAP_PIN_HEIGHT = 5;
